#!/bin/sh
set -e

DOCKER_REGISTRY_IMAGE=${INPUT_DOCKER_REGISTRY}/${GITHUB_REPOSITORY}
DOCKER_REGISTRY_IMAGE_BUILD=${DOCKER_REGISTRY_IMAGE}/${GITHUB_SHA}
DOCKER_REGISTRY_IMAGE_DEV=${DOCKER_REGISTRY_IMAGE_BUILD}:dev

echo ${INPUT_DOCKER_REGISTRY_PASSWORD} | docker login -u ${INPUT_DOCKER_REGISTRY_USER} --password-stdin ${INPUT_DOCKER_REGISTRY}

docker build -t ${DOCKER_REGISTRY_IMAGE_BUILD} .
docker push ${DOCKER_REGISTRY_IMAGE_BUILD}
docker tag ${DOCKER_REGISTRY_IMAGE_BUILD} ${DOCKER_REGISTRY_IMAGE_DEV}
docker push ${DOCKER_REGISTRY_IMAGE_DEV}
